version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --s3-bucket prtis --region us-east-1 --output-template-file packaged-template.yml
      - npm install --prefix ./mockservice-static-website
      - npm run build --prefix ./mockservice-static-website
artifacts:
  files:
    - packaged-template.yml