version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --s3-bucket prtis --region us-east-1
artifacts:
  files:
    - packaged-template.yml