version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket prtis --output-template-file packaged-template.yml --region us-east-1
artifacts:
  files:
    - packaged-template.yml