version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mockservice-api-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-h11om2he2mau"
s3_prefix = "mockservice-api-serverless"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
